// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.1
// source: proto/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestReadConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromId       string `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromNickname string `protobuf:"bytes,2,opt,name=from_nickname,json=fromNickname,proto3" json:"from_nickname,omitempty"`
	Content      string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *RequestReadConfig) Reset() {
	*x = RequestReadConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestReadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReadConfig) ProtoMessage() {}

func (x *RequestReadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReadConfig.ProtoReflect.Descriptor instead.
func (*RequestReadConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *RequestReadConfig) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *RequestReadConfig) GetFromNickname() string {
	if x != nil {
		return x.FromNickname
	}
	return ""
}

func (x *RequestReadConfig) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReplyReadConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Count   uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Msg     *Msg   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ReplyReadConfig) Reset() {
	*x = ReplyReadConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyReadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReadConfig) ProtoMessage() {}

func (x *ReplyReadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReadConfig.ProtoReflect.Descriptor instead.
func (*ReplyReadConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyReadConfig) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReplyReadConfig) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyReadConfig) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReplyReadConfig) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Fail    string `protobuf:"bytes,2,opt,name=fail,proto3" json:"fail,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *Msg) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *Msg) GetFail() string {
	if x != nil {
		return x.Fail
	}
	return ""
}

var File_proto_config_config_proto protoreflect.FileDescriptor

var file_proto_config_config_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x11, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x6d, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4d,
	0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x33, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x32, 0x3e, 0x0a, 0x06,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x34, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x10, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_config_config_proto_rawDescOnce sync.Once
	file_proto_config_config_proto_rawDescData = file_proto_config_config_proto_rawDesc
)

func file_proto_config_config_proto_rawDescGZIP() []byte {
	file_proto_config_config_proto_rawDescOnce.Do(func() {
		file_proto_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_config_config_proto_rawDescData)
	})
	return file_proto_config_config_proto_rawDescData
}

var file_proto_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_config_config_proto_goTypes = []interface{}{
	(*RequestReadConfig)(nil), // 0: RequestReadConfig
	(*ReplyReadConfig)(nil),   // 1: ReplyReadConfig
	(*Msg)(nil),               // 2: Msg
}
var file_proto_config_config_proto_depIdxs = []int32{
	2, // 0: ReplyReadConfig.msg:type_name -> Msg
	0, // 1: Config.ReadConfig:input_type -> RequestReadConfig
	1, // 2: Config.ReadConfig:output_type -> ReplyReadConfig
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_config_config_proto_init() }
func file_proto_config_config_proto_init() {
	if File_proto_config_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_config_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestReadConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyReadConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_config_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_config_proto_goTypes,
		DependencyIndexes: file_proto_config_config_proto_depIdxs,
		MessageInfos:      file_proto_config_config_proto_msgTypes,
	}.Build()
	File_proto_config_config_proto = out.File
	file_proto_config_config_proto_rawDesc = nil
	file_proto_config_config_proto_goTypes = nil
	file_proto_config_config_proto_depIdxs = nil
}
